import Head from "next/head";
import Hero from "./components/hero";
import Projects from "./components/projects";
import Blog from "../pages/blog";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs 12s</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Projects />
        <Blog />
      </main>
    </>
  );
}
